Auto Checkin

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -1,52 +1,56 @@
-#!/bin/sh
+#!/bin/bash
+# shellcheck disable=SC1091
 
-# Custom INIT for Community Linux INITRD
-#
-# Breakpoint flags that may be introduced from the kernel command line:
-#    ramfs=cmdline       cmdline       "Break at the beginning of script"
-#    ramfs=initqueue     initqueue     "Break before initqueue"
-#    ramfs=pre-mount     pre-mount     "Break pre-mount"
-#    ramfs=pre-overlay   overlay       "Break before overlay"
-#    ramfs=pre-chroot    switch_root   "Break before switch_root"
-#
-# Arguments that may be introduced from the kernel command line:
-#
-#    preinit=initprog    program name   "The pre-init program to execute"
-#
-# History:
-#           Tue 24.Dec.2024     Reworked 64 bit
-#           Sun 29.Dec.2024     Mount CD simplified
-#           Thu 16.Jan.2025     PreInit command line arguments added
-
-# Silence async messages on terminal
-/usr/bin/setterm --msg off
+# Custom INIT for Community Linux INITRD / INITRAMFS.
+# See doc in init.doc.txt
 
 # This also signals that we are active
-echo "COMMUNITY LINUX 64 Version 1.0.0\n"
-echo "Loaded kernel ... \033[32;1mOK\033[0m "
+echo
+echo "Booting Community Linux 64 Version 1.0.0, built on Thu 20.Mar.2025"
+echo
 
-export PATH=/sbin:/bin:/usr/sbin:/usr/bin
+# See if we are in simulation by looking at GUI files
+#   (which do not run at yet in real boot)
+#INSIM=$(pgrep Xorg)
+#echo "insim" $INSIM
+#if [  "$INSIM" != "" ] ; then
+#   echo Warn: in simulation $INSIM
+#   Optional test / simulate vars
+#   VERBOSE=3 ; TESTME=1
+#else
+#    echo real exec
+#fi
 
-mkdir -p /proc /sys /dev/pts
-
-# Mount some basic things
-mount -t proc -o  nosuid,noexec,nodev proc /proc >/dev/null 2>&1
-mount -t sysfs -o nosuid,noexec,nodev sysfs /sys >/dev/null 2>&1
-mount -t devpts -o nosuid,noexec,nodev  devpts /dev/pts >/dev/null 2>&1
-
-# Load out lib
-. /lib/shlib/comlin.sh
-
-getargs 'verbose' && export VERBOSE=$FOUNDVAL
-
-getarg 'ramfs=cmdline' && temporary_shell -n cmdline "Break at the beginning of script"
-
+# Silence async messages on terminal
 export TERM=linux
+/usr/bin/setterm --msg off
 export USER=root
 export HOME=/root
 
-# This is a trick to get rid of this shell and exec the next stage
+printf "Loaded kernel ... \033[32;1mOK\033[0m \n"
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin
+
+mkdir -p /dev/pts
+
+# Mount some basic things
+mkdir -p /proc ; mount -t proc proc /proc
+mkdir -p /sys ; mount -t sysfs sysfs /sys
+
+# Devices go here
+mount -t devtmpfs devtmpfs /dev
+udevadm settle
+mount -t devpts -o nosuid,noexec,nodev devpts /dev/pts
+
+# Load our lib
+. /lib/shlib/comlin.sh
+
+getargs 'verbose' && export VERBOSE="$FOUNDVAL"
+getarg 'ramfs=cmdline' && temporary_shell -n cmdline "Break at the beginning of script"
+
 trap "temporary_shell Signal caught!" 0
+trap "echo Stopping temporarily" 2
+
+#trap "echo Stopping temporarily, type exit to continue; temporary_shell \"CTRL-C caught!\" " 2
 
 CDROOT="/cdroot"
 NEWROOT="/sysroot"
@@ -57,28 +61,31 @@ TMPROOT=/tmp
 # Just to make sure
 ln -s /proc/self/fd /dev/fd >/dev/null 2>&1
 
-#UDEVVERSION=$(udevadm --version)
-# start up udev and trigger cold plugs
-#udevd --daemon #--resolve-names=never
-#UDEV_LOG_PRIO_ARG=--log-priority
-#UDEV_QUEUE_EMPTY="udevadm settle --timeout=0"
-#
-#if [ $UDEVVERSION -lt 140 ]; then
-#   UDEV_LOG_PRIO_ARG=--log_priority
-#   UDEV_QUEUE_EMPTY="udevadm settle --timeout=1"
-#fi
+# Load modules needed
+loadmods
 
-#getarg 'ramfs=initqueue' && temporary_shell -n initqueue "Break before initqueue"
+getarg 'ramfs=systemd' && temporary_shell -n systemd "Break before systemd"
+
+# Start udev and execute trigger for a rescan
+WASSYSD=$(pgrep systemd-udevd)
+if [ -n "$WASSYSD" ] ; then
+    /lib/systemd/systemd-udevd --daemon
+fi
+
+udevadm trigger -c add -t subsystems
+udevadm settle
+udevadm trigger -c add -t devices
+udevadm settle
+partprobe
 
 # Pre-mount happens before we try to mount the root filesystem
 getarg 'ramfs=pre-mount' && temporary_shell -n pre-mount "Break pre-mount"
 
-# Mount scripts actually try to mount the root filesystem, and may
-# be sourced any number of times. As soon as one suceeds, no more are sourced.
+printf "Mounting media ... "
 
+# Mount scripts actually try to mount the root filesystem,
 ii=0
 while :; do
-
     # If no root, search for it, else accept command line
     if [ -z "$root" ] ; then
         MOUNT_DEVICE=""
@@ -88,32 +95,39 @@ while :; do
     fi
 
     # No ROOT FS found, tell the user
-    if test -z $MOUNT_DEVICE ; then
-        echo "Cannot find a valid system image - dropping to shell."
-        echo "Exiting this shell re-scans drives for valid system image."
-        temporary_shell  "No CD drive found."
+    if [ -z "$MOUNT_DEVICE" ] ; then
+        echo "Cannot find a marked and valid COMLIN system image - dropping to shell."
+        echo "Exiting this shell re-scans drives for valid system image.", $ii
+        temporary_shell  "No USB/CD drive found."
     else
-        # Done here
+        #DELAYONE Done here
         break
     fi
-    ii=$(($ii+1))
-    # Give up after many tries
-    [ $ii -gt 20 ] \
-        && { flock -s 9 ; temporary_shell "Can't mount root filesystem"; } \
-            9>/.console_lock
+    ii=$((ii+1))
+    # Give up after many tries (and test mode)
+    if [ $ii -gt 5 ] ; then
+        temporary_shell "Can't mount root filesystem"
+        break
+    fi
 done
 
-#echo "Mounted $MOUNT_DEVICE filesystem on $CDROOT"
+if [ $((VERBOSE)) -gt 1 ] ; then
+    echo "Mounted $MOUNT_DEVICE filesystem on $CDROOT"
+fi
+
+printf "\033[32;1mOK\033[0m \n"
 
 # By the time we get here, the root filesystem should be mounted.
 # Try to find init.
 
 for ii in "$(getarg init=)"/sbin/preinit /sbin/init /init /etc/init /bin/sh; do
     #echo "Search $CDROOT$ii"
-    [ -f "$CDROOT$ii" -a -x "$CDROOT$ii" ] && { INIT="$ii"; break; }
+    [ -f "$CDROOT$ii" ] && [ -x "$CDROOT$ii" ] && { INIT="$ii"; break; }
 done
 
-#echo "POST init search: $INIT"
+if [ $((VERBOSE)) -gt 1 ] ; then
+    echo "POST init search: $INIT"
+fi
 
 [ "$INIT" ] || {
     echo "Cannot find CD init!"
@@ -124,8 +138,6 @@ done
 mount -t tmpfs -o tmpfs $NEWROOT  >/dev/null 2>&1
 
 touch /etc/fstab
-
-#export PS1="initramfs before overlay " ; setsid -c -w /bin/bash
 
 mount -t tmpfs -o tmpfs $TMPROOT  >/dev/null 2>&1
 
@@ -138,6 +150,12 @@ mkdir -p $TMPROOT/fs
 
 getarg 'ramfs=pre-overlay' && temporary_shell -n overlay "Break before overlay"
 
+if [  "$INSIM" != "" ] ; then
+    exit
+fi
+
+mkdir -p $NEWROOT/dev/pts
+
 mount -t overlay  comlin_overlay  \
         -olowerdir=$CDROOT,upperdir=$TMPROOT/fs,workdir=$TMPROOT/work \
         $NEWROOT
@@ -147,33 +165,33 @@ mount -t overlay  comlin_overlay  \
 #pivot_root . $OLDROOT
 
 # Copy it so pre-init can see it
-echo $CMDLINE >$NEWROOT/var/cmdline
+echo "$CMDLINE" >$NEWROOT/var/cmdline
 
 getarg 'ramfs=pre-del' && temporary_shell -n del_initram "Break before init_ram"
 
 # Del unneeded files ... should release appx 80 megs (not much)
-rm -rf lib/modules
-rm -rf lib/firmware
-rm -rf lib/systemd
-rm -rf sbin
-rm -rf usr/sbin
+# We deal with it later ...
 
-#rm -rf dev/*
-#mknod -m 0666 /dev/null c 1 3   # Put it back for now
+#if [  "$INSIM" != "" ] ; then
+#    rm -rf lib/modules
+#    rm -rf lib/firmware
+#    rm -rf lib/systemd
+#    rm -rf sbin
+#    rm -rf usr/sbin
+#fi
 
-mkdir -p $NEWROOT/proc $NEWROOT/sys $NEWROOT/dev/ $NEWROOT/dev/pts
-mount --bind /proc $NEWROOT/proc
-mount --bind /sys $NEWROOT/sys
-mount --bind /dev/pts $NEWROOT/dev/pts
+getarg 'ramfs=pre-chroot' && temporary_shell \
+            -n switch_root "Break before switch_root"
 
-getarg 'ramfs=pre-chroot' && temporary_shell -n switch_root "Break before switch_root"
+# We deal with it later ...
+#if [  "$INSIM" != "" ] ; then
+#    rm -rf usr/bin
+#    rm -rf bin
+#fi
 
-rm -rf usr/bin
-rm -rf bin
+info "Jumping to preinit ... "
 
-#info "Switching root"
-
-cd $NEWROOT
+cd $NEWROOT || echo Failed to change root
 
 getargs 'preinit='
 if [ "" = "$FOUNDCMD" ]; then
@@ -185,11 +203,5 @@ fi
 
 # Tried exec in chroot ... no go (script does not have this feature)
 exec ./usr/sbin/chroot . $FOUNDCMD
-
-# If anything went wrong ... cycle here
-while :; do
-   export PS1="initramfs error $ " ; setsid -c -w /bin/bash
-   echo "Spawning new shell ... "
-done
 
 # EOF
diff --git a/preinit/postinit b/preinit/postinit
--- a/preinit/postinit
+++ b/preinit/postinit
@@ -1,18 +1,20 @@
 #!/bin/bash
-# shellcheck disable=SC2004,SC2009,SC2068,SC2002
-# shellcheck disable=SC1091,SC2086
+# shellcheck disable=SC1091
 
-if [ $(($TESTME)) -gt 0 ] ; then
+
+if [ $((TESTME)) -gt 0 ] ; then
     .  ./preinit.sh
 else
     .  /sbin/preinit.sh
 fi
 
+loginfo Postinit stage ...
+
 # Determine overall flags for operation (for this file)
 getargy 'verbose' && export VERBOSE=$FOUNDVAL
 getargx 'ibreak=all' && export BREAKALL=1
 
-if [ $(($VERBOSE)) -gt 0 ] ; then
+if [ $((VERBOSE)) -gt 0 ] ; then
     echo "COMLIN64 in final stage"
 fi
 
@@ -22,12 +24,27 @@ export SYSTEMD_IGNORE_CHROOT=1
 # UP loopback network connection
 ifconfig lo up 127.0.0.1
 
-# May have residual from prev run
+mkdir -p /proc /sys /dev
+# Remount for devices
+mkdir -p /proc ; mount -t proc proc /proc
 
+# Remount if not present
+if [ ! -d /sys/kernel ] ; then
+    mount -t sysfs sysfs /sys
+fi
+
+if [ "$(mount | grep /dev)" == "" ] ; then
+    mount -t devtmpfs devtmpfs /dev
+fi
+
+# May have residuals from prev run
 rm -rf /dev/snd/*
 rm -rf /run/dbus/*
 
-# We create this dynamically
+# Test alternate config
+#export XDG_CONFIG_DIR=/etc/xdg-comlin
+
+# Create this dynamically
 export XDG_RUNTIME_DIR=/run/user/$UID
 mkdir -p $XDG_RUNTIME_DIR
 
@@ -39,28 +56,22 @@ echo -e " \033[32;1mOK\033[0m"
 
 # Start logging
 echo -n "Starting rsyslogd ... "
+rm -f /run/rsyslogd.pid
 rsyslogd >> "$SULOUT" 2>> "$SULERR" &
 getargy 'isleep' && sleep "$FOUNDVAL"
 echo -e " \033[32;1mOK\033[0m"
 
 dbus-daemon --session >/dev/null 2>&1 &
 
-# Virtual terminals and a serial port
-getargx 'ibreak=vt' && tmpshell "$FOUNDVAR $ "
-echo -n "Starting VTs ... "
-startvts
-getargy 'isleep' && sleep "$FOUNDVAL"
-echo -e " \033[32;1mOK\033[0m"
-
 getargx 'ibreak=polkit' && tmpshell "$FOUNDVAR $ "
 echo -n "Starting polkit ... "
-/usr/libexec/polkitd >>$SULOUT 2>>$SULERR &
+/usr/libexec/polkitd >>"$SULOUT" 2>>"$SULERR" &
 getargy 'isleep' && sleep "$FOUNDVAL"
 echo -e " \033[32;1mOK\033[0m"
 
 getargx 'ibreak=udevd' && tmpshell "$FOUNDVAR $ "
 echo -n "Starting systemd-udevd ... "
-/lib/systemd/systemd-udevd >>$SULOUT 2>>$SULERR &
+/lib/systemd/systemd-udevd >>"$SULOUT" 2>>"$SULERR" &
 getargy 'isleep' && sleep "$FOUNDVAL"
 echo -e " \033[32;1mOK\033[0m"
 
@@ -77,18 +88,47 @@ getargy 'isleep' && sleep "$FOUNDVAL"
 echo -e " \033[32;1mOK\033[0m"
 
 rm -rf /var/run/pulse/pid
-rm -rf .config/pulse/.
+rm -rf .config/pulse/*
 
-#echo -n "Pulseaudio daemon ... "
-#pulseaudio --deaemonize=no --system --realtime  >>$SULOUT 2>>$SULERR  &
+# Second round for dependents (like: WIFI)
+
+echo -n "Finalizing devices  ... "
+
+udevadm trigger -c add -t subsystems
+udevadm settle
+udevadm trigger -c add -t devices
+udevadm settle
+
+loadmods
+udevadm settle
+loaddevs
+udevadm settle
+loadmods
+udevadm settle
+
+echo -e " \033[32;1mOK\033[0m"
+
+mkdir -p /dev/pts ; mount -t devpts devpts /dev/pts
+
+getargx 'ibreak=pre-acpi' && tmpshell  "$FOUNDVAR $ "
+echo -n "Starting acpid ... "
+/usr/sbin/acpid >>"$SULOUT" 2>>"$SULERR" &
+
+getargy 'isleep' && sleep "$FOUNDVAL"
+echo -e " \033[32;1mOK\033[0m"
+
+echo -n "Pulseaudio daemon ... "
+mkdir -p /dev/shm
+pulseaudio --deaemonize=no --system --realtime  >>"$SULOUT" 2>>"$SULERR"  &
 #pactl set-sink-mute 0 0  >>$SULOUT 2>>$SULERR
 #pactl set-sink-volume 0 0.5  >>$SULOUT 2>>$SULERR
-#getargy 'isleep' && sleep "$FOUNDVAL"
-#echo -e " \033[32;1mOK\033[0m"
+getargy 'isleep' && sleep "$FOUNDVAL"
+echo -e " \033[32;1mOK\033[0m"
 
 getargx 'ibreak=network' && tmpshell "$FOUNDVAR $ "
 echo -n "Starting network ... "
 dhclient >>"$SULOUT" 2>>"$SULERR" &
+NetworkManager
 getargy 'isleep' && sleep "$FOUNDVAL"
 echo -e " \033[32;1mOK\033[0m"
 
@@ -98,39 +138,52 @@ echo -n "Starting sshd ... "
 getargy 'isleep' && sleep "$FOUNDVAL"
 echo -e " \033[32;1mOK\033[0m"
 
-getargx 'ibreak=pre-user' && tmpshell  "$FOUNDVAR $ "
+# This is a precaution, comment out if not wanted
+/usr/sbin/thermald
+
+# Our power key watcher
+/usr/bin/powacpi &
 
 SDCOM="/var/tmp/.shutdowncmd"
 
-# Bye Bye root
+# Bye Bye old root
 NEWHOME="/root"
 mkdir -p $NEWHOME
 cd $NEWHOME || echo "Cannot change to $NEWHOME"
 
-# Xorg needs these
+# Xorg needs these clean
 rm -f /tmp/.X*lock
 rm -rf /tmp/.X11-unix
 
 export XAUTHORITY=$NEWHOME/.Xauthority
 export ICEAUTHORITY=$NEWHOME/.ICEauthority
-#export DISPLAY=:0
-
 export XAUTHLOCALHOSTNAME=localhost
 
 while : ; do
     rm -f $SDCOM                # Fresh start
-    getargy 'isleep' && sleep "$FOUNDVAL"
     getargx 'ibreak=pre-gui' && tmpshell  "$FOUNDVAR $ "
 
-    # Start initial GUI for login program 'pylogin'
-    xinit # >.x_out 2>.x_err
+    printf "Starting GUI, \033[34;1m(in progress)\033[0m ... "
 
     # Start Xorg as root
     #/usr/bin/startxfce4 -- -keeptty vt5 >.xfce_out 2>.xfce_err
 
+    stty -g >.stty_dump.txt
+
+    # Start initial GUI for login program 'pylogin'
+    xinit -- -keeptty vt5  >.xorg_out 2>.xorg_err
+
+    getargy 'isleep' && sleep "$FOUNDVAL"
+
+    cd $NEWHOME || echo "Cannot change to $NEWHOME"
+
     # Back to initial terminal
     chvt 1
-    echo -e " \033[32;1mOK\033[0m"
+    # Sadly, this was needed, as the terminal was messed up (Xorg bug?)
+    stty "$(cat .stty_dump.txt)"
+    stty sane
+
+    echo -e " \033[32;1mDone\033[0m"
 
     getargx 'ibreak=post-gui' &&  tmpshell "$FOUNDVAR $ "
 
@@ -140,22 +193,19 @@ while : ; do
         getargx 'ibreak=post-cleanup' && tmpshell "Post cleanup $ "
     fi
 
-    # If it got here, it is a logout or shutdown error
-    echo "Type:     'exit' to restart the X session"
+    # If it got here, it is a GUI Exit / Logout
+    echo
+    echo "---------------------------------------------------"
+    echo "Type:     'exit' (or Ctrl-D) to start a new X session / login"
     echo "          'linux_reboot -f' to restart computer."
     echo "          'linux_poweroff -f' to power down computer."
-    #tmpshell "XFCE loop iteration $ "
+    echo "---------------------------------------------------"
+    echo
+
     tmpshell "System Control Prompt $ "
+
 done
 
-# Can not reach this ... just in case
-
-# Start a shell for recovery / diagnosis
-export PS1="Comlin PostInit fallback: \w $ "
-while : ; do
-   echo "Spawning new shell $$ \w # "
-   setsid -c -w /bin/bash
-   sleep 1
-done
+# Can not reach this ...
 
 # EOF
diff --git a/scripts/make_initramfs b/scripts/make_initramfs
--- a/scripts/make_initramfs
+++ b/scripts/make_initramfs
@@ -24,22 +24,29 @@ if [ ! -f $KEYGET ] ; then
     exit 1;
 fi
 
+# Exit if check fails
+
+exit_if_fail() {
+
+    $1 $2; ERR=$?
+
+    if [ "$ERR" != "0" ] ; then
+        echo "Error in $2"
+        exit 1
+    fi
+}
+
 if [ ! -d $INITRAMFSDIR ]; then
     echo "No initramfs files yet."
     exit 1
 fi
 
-# Syntax check init
-bash -n $INITRAMFSDIR/init; ERR=$?
-if [ "$ERR" != "0" ] ; then
-    echo "Syntax error in init"
-    exit 1
-fi
-bash -n $INITRAMFSDIR/lib/shlib/comlin.sh; ERR=$?
-if [ "$ERR" != "0" ] ; then
-    echo "Syntax error in comlin.sh"
-    exit 1
-fi
+# Syntax check
+exit_if_fail "bash -n" $INITRAMFSDIR/init
+exit_if_fail "bash -n" $INITRAMFSDIR/lib/shlib/comlin.sh
+
+exit_if_fail shellcheck $INITRAMFSDIR/init
+exit_if_fail shellcheck $INITRAMFSDIR/lib/shlib/comlin.sh
 
 # Gather some COMLIN apps into initramfs
 
diff --git a/scripts/make_iso b/scripts/make_iso
--- a/scripts/make_iso
+++ b/scripts/make_iso
@@ -34,19 +34,25 @@ if [ ! -f $KERNELDIR/initramfs ] ; then
     exit 1
 fi
 
-if [ ! -f ./boot/grub/grub.conf ] ; then
+if [ ! -f ./boot/grub/grub.cfg ] ; then
     echo "Execute 'make getboot' first."
     exit 1
 fi
 
 rm -f $ROOTISOFILE.part
 touch $ROOTISOFILE.part
-scripts/progress.sh $ROOTISOFILE.part &
+#scripts/progress.sh $ROOTISOFILE.part &
 
-echo -n "Making $ROOTISOFILE ($ROOTISOFILE.part) ... "
-mkisofs -input-charset utf-8 -R -b boot/grub/stage2_eltorito -no-emul-boot  \
-         -boot-load-size 4 -boot-info-table -o $ROOTISOFILE.part \
-         -quiet $ROOTFS  || fail
+#echo -n "Making $ROOTISOFILE ($ROOTISOFILE.part) ... "
+#mkisofs  -input-charset utf-8 -R -b boot/grub/stage2_eltorito -no-emul-boot  \
+#         -boot-load-size 4 -boot-info-table -o $ROOTISOFILE.part \
+#         -quiet $ROOTFS  || fail
+#echo
+#echo OK
+
+echo -n "Making ISO grub rescue $ROOTISOFILE ($ROOTISOFILE.part) ... "
+grub-mkrescue  --product-name "Comlin64" -o $ROOTISOFILE.part $ROOTFS
+
 echo
 echo OK
 
