Auto Checkin

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -2,12 +2,17 @@
 
 # Custom INIT for Community Linux
 
-. shlib/functions.sh
-. shlib/dracut-lib.sh
+# History:
+#           Tue 24.Dec.2024         Reworked 64 bit
 
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin
 export TERM=linux
+
 NEWROOT="/sysroot"
+OLDROOT="/var/oldroot"
+
+. shlib/functions.sh
+. shlib/comlin.sh
 
 # Patch missing stuff
 #mknod /dev/sr0 b 11 0
@@ -34,19 +39,19 @@ MYFST=ext4
 mount -t proc -o nosuid,noexec,nodev proc /proc >/dev/null 2>&1
 mount -t sysfs -o nosuid,noexec,nodev sysfs /sys >/dev/null 2>&1
 
-# Mount CDROM
-#mkdir /mnt/cdrom
-#mount /dev/sr0 /mnt/cdrom
+# Silence async messages on terminal
+setterm --msg off
+#--msglevel 0
 
 # This was needed so the TSC calibration completes ARGGGHH
 sleep 1
 
-keyget -t 3 "Entering InitRamFS, presee Enter to drop to shell"
-if [ $? -eq 0 ] ; then
-    echo Dropping to pre scan shell ..
-    # Set session ID and execute bash
-    setsid -c -w /bin/bash
-fi
+#keyget -t 3 "Entering InitRamFS init, press Enter to drop to shell"
+#if [ $? -eq 0 ] ; then
+#    echo Dropping to pre scan shell ..
+#    # Set session ID and execute bash
+#    setsid -c -w /bin/bash
+#fi
 
 #if [ ! -c /dev/ptmx ]; then
 #    # Try to mount devtmpfs
@@ -79,7 +84,7 @@ mkdir -p /dev/pts
 mount -t devpts -o gid=5,mode=620 devpts /dev/pts >/dev/null 2>&1
 
 mkdir -p /dev/shm
-mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs /dev/shm >/dev/null
+mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs /dev/shm >/dev/null 2>&1
 
 UDEVVERSION=$(udevadm --version)
 
@@ -87,7 +92,7 @@ source_conf /etc/conf.d
 
 # Run scriptlets to parse the command line
 getarg 'rdbreak=cmdline' && emergency_shell -n cmdline "Break before cmdline"
-source_all cmdline
+#source_all cmdline
 
 # As we are searching for root, no checking
 #[ -z "$root" ] && die "No or empty root= argument"
@@ -106,7 +111,7 @@ source_all cmdline
 
 # pre-udev scripts run before udev starts, and are run only once.
 getarg 'rdbreak=pre-udev' && emergency_shell -n pre-udev "Break before pre-udev"
-source_all pre-udev
+#source_all pre-udev
 
 # start up udev and trigger cold plugs
 udevd --daemon --resolve-names=never
@@ -123,7 +128,7 @@ getarg rdudevinfo && udevadm control $UDEV_LOG_PRIO_ARG=info
 getarg rdudevdebug && udevadm control $UDEV_LOG_PRIO_ARG=debug
 
 getarg 'rdbreak=pre-trigger' && emergency_shell -n pre-trigger "Break before pre-trigger"
-source_all pre-trigger
+#source_all pre-trigger
 
 # Then the rest
 udevadm trigger --action=add $udevtriggeropts  >/dev/null 2>&1
@@ -143,41 +148,41 @@ while :; do
     udevsettle
     check_finished && break
 
-    if [ -f /initqueue/work ]; then
-        rm /initqueue/work
-    fi
+    #if [ -f /initqueue/work ]; then
+    #    rm /initqueue/work
+    #fi
 
-    for job in /initqueue/*.sh; do
-    [ -e "$job" ] || break
-        job=$job . $job
-        check_finished && break 2
-    done
+    #for job in /initqueue/*.sh; do
+    #[ -e "$job" ] || break
+    #    job=$job . $job
+    #    check_finished && break 2
+    #done
 
-    $UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
-    modprobe scsi_wait_scan && rmmod scsi_wait_scan
-    $UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
+    #$UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
+    #modprobe scsi_wait_scan && rmmod scsi_wait_scan
+    #$UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
 
-    for job in /initqueue-settled/*.sh; do
-        [ -e "$job" ] || break
-        job=$job . $job
-        check_finished && break 2
-    done
-
-    $UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
-
+    #for job in /initqueue-settled/*.sh; do
+    #    [ -e "$job" ] || break
+    #    job=$job . $job
+    #    check_finished && break 2
+    #done
+    #
+    #$UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
+    #
     # no more udev jobs and queues empty.
-    sleep 0.5
+    #sleep 0.5
 
     # dirty hack for some cdrom drives,
     # which report no medium for quiet
     # some time.
-    for cdrom in /sys/block/sr*; do
-        [ -e "$cdrom" ] || continue
-        # skip, if cdrom medium was already found
-            strstr "$(udevadm info --query=env --path=${cdrom##/sys})" \
-            ID_CDROM_MEDIA && continue
-            echo change > "$cdrom/uevent"
-    done
+    #for cdrom in /sys/block/sr*; do
+    #    [ -e "$cdrom" ] || continue
+    #    # skip, if cdrom medium was already found
+    #        strstr "$(udevadm info --query=env --path=${cdrom##/sys})" \
+    #        ID_CDROM_MEDIA && continue
+    #        echo change > "$cdrom/uevent"
+    #done
 
     if [ $main_loop -gt $(($RDRETRY/2)) ]; then
     for job in /initqueue-timeout/*.sh; do
@@ -203,7 +208,7 @@ unset RDRETRY
 # Pre-mount happens before we try to mount the root filesystem
 
 getarg 'rdbreak=pre-mount' && emergency_shell -n pre-mount "Break pre-mount"
-source_all pre-mount
+#source_all pre-mount
 
 getarg 'rdbreak=mount' && emergency_shell -n mount "Break mount"
 
@@ -213,8 +218,7 @@ getarg 'rdbreak=mount' && emergency_shell -n mount "Break mount"
 i=0
 while :; do
 
-    echo "Attempting Mount"
-
+    #echo "Attempting Mount"
     #[ -d "$NEWROOT/proc" ] && break;
     #for f in /mount/*.sh; do
     #   [ -f "$f" ] && . "$f"
@@ -247,25 +251,39 @@ while :; do
         && { flock -s 9 ; emergency_shell "Can't mount root filesystem"; } 9>/.console_lock
 done
 
-echo "Mounted root filesystem on " $DEVICE
+echo "Mounted $DEVICE filesystem on $NEWROOT"
 
+# Make sure standard items exist
+#[ -e /dev/console ] || ln -s /dev/tty0 /dev/console
+
+# Mount some important things
+#mount -t proc -o nosuid,noexec,nodev proc /proc >/dev/null 2>&1
+#mount -t sysfs -o nosuid,noexec,nodev sysfs /sys >/dev/null 2>&1
+#ln -s /proc/self/fd /dev/fd >/dev/null 2>&1
+#mkdir -p /dev/pts
+#mount -t devpts -o gid=5,mode=620 devpts /dev/pts >/dev/null 2>&1
+#mkdir -p /dev/shm
+#mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs /dev/shm >/dev/null
 #{
 #    while read dev mp rest; do [ "$mp" = "$NEWROOT" ] && echo $dev; done < /proc/mounts
 #} | vinfo
 
-#dosh
-
 # Pre pivot scripts are sourced just before we switch over to the new root.
 
 getarg 'rdbreak=pre-pivot' && emergency_shell -n pre-pivot "Break pre-pivot"
-source_all pre-pivot
+#source_all pre-pivot
+
+#echo post pre-pivot source
 
 # By the time we get here, the root filesystem should be mounted.
 # Try to find init.
 
-for i in "$(getarg init=)" /sbin/init /etc/init /init /bin/sh; do
-    [ -f "$NEWROOT$i" -a -x "$NEWROOT$i" ] && { INIT="$i"; break; }
+for ii in "$(getarg init=)" /sbin/init /etc/init /init /bin/sh; do
+    #echo "Search $NEWROOT$ii"
+    [ -f "$NEWROOT$ii" -a -x "$NEWROOT$ii" ] && { INIT="$ii"; break; }
 done
+
+#echo "POST init search: $INIT"
 
 [ "$INIT" ] || {
     echo "Cannot find init!"
@@ -287,74 +305,101 @@ while pidof udevd >/dev/null 2>&1; do
 done
 
 # Clean up the environment
-for i in $(export -p); do
-    i=${i#declare -x}
-    i=${i#export}
-    i=${i%%=*}
-    [ "$i" = "root" -o "$i" = "PATH" -o "$i" = "HOME" -o "$i" = "TERM" ] || unset $i
-done
+#for i in $(export -p); do
+#    i=${i#declare -x}
+#    i=${i#export}
+#    i=${i%%=*}
+#    [ "$i" = "root" -o "$i" = "PATH" -o "$i" = "HOME" -o "$i" = "TERM" ] || unset $i
+#done
 
 initargs=""
 
-read CLINE </proc/cmdline
-if getarg init= >/dev/null ; then
-    ignoreargs="console BOOT_IMAGE"
-    # only pass arguments after init= to the init
-    CLINE=${CLINE#*init=}
-    set $CLINE
-    shift
-    for x in "$@"; do
-        for s in $ignoreargs; do
-            [ "${x%%=*}" = $s ] && continue 2
-        done
-        initargs="$initargs $x"
-    done
-    unset CLINE
-else
-    set $CLINE
-    shift
-    for x in "$@"; do
-        case "$x" in
-            [0-9]|s|S|single|emergency|auto )
-                initargs="$initargs $x"
-            ;;
-        esac
-    done
-fi
+#echo before read cmdline
+#read CLINE </proc/cmdline
+#if getarg init= >/dev/null ; then
+#    ignoreargs="console BOOT_IMAGE"
+#    # only pass arguments after init= to the init
+#    CLINE=${CLINE#*init=}
+#    set $CLINE
+#    shift
+#    for x in "$@"; do
+#        for s in $ignoreargs; do
+#            [ "${x%%=*}" = $s ] && continue 2
+#        done
+#        initargs="$initargs $x"
+#    done
+#    unset CLINE
+#else
+#    set $CLINE
+#    shift
+#    for x in "$@"; do
+#        case "$x" in
+#            [0-9]|s|S|single|emergency|auto )
+#                initargs="$initargs $x"
+#            ;;
+#        esac
+#    done
+#fi
+
+#echo after read cmdline
 
 # Debug: Copy state
-if getarg rdcopystate; then
-    [ -d /dev/.initramfs/ ] || mkdir /dev/.initramfs/
-    cp /tmp/* /dev/.initramfs/ >/dev/null 2>&1
-fi
+#if getarg rdcopystate; then
+#    [ -d /dev/.initramfs/ ] || mkdir /dev/.initramfs/
+#    cp /tmp/* /dev/.initramfs/ >/dev/null 2>&1
+#fi
 
 info "Switching root"
 
-#wait_for_loginit
+wait_for_loginit
 
-keyget -t 3 "About to switch root, Press Enter within 3 seconds to drop to shell"
-if [ $? -eq 0 ] ; then
-    echo
-    echo "Dropping to Shell"
-    setsid -c -w /bin/bash
-    echo
-fi
+#keyget -t 3 "About to switch root, Press Enter within 3 seconds to drop to shell"
+#if [ $? -eq 0 ] ; then
+#    echo
+#    echo "Dropping to Shell"
+#    setsid -c -w /bin/bash
+#    echo
+#fi
 
-if [ -f /etc/capsdrop ]; then
-    . /etc/capsdrop
-    info "Calling $INIT with capabilities $CAPS_INIT_DROP dropped."
-    exec capsh --drop="$CAPS_INIT_DROP" -- -c "exec switch_root \"$NEWROOT\" \"$INIT\" $initargs" || {
-    warn "Command:"
-    warn capsh --drop=$CAPS_INIT_DROP -- -c "'"exec switch_root "$NEWROOT" "$INIT" $initargs"'"
-    warn "failed."
-    emergency_shell
-    }
-else
-    exec switch_root "$NEWROOT" "$INIT" $initargs || {
-    warn "Something went very badly wrong in the initramfs.  Please "
-    warn "file a bug against dracut."
-    emergency_shell
-    }
-fi
+#if [ -f /etc/capsdrop ]; then
+#    . /etc/capsdrop
+#    info "Calling $INIT with capabilities $CAPS_INIT_DROP dropped."
+#    exec capsh --drop="$CAPS_INIT_DROP" -- -c "exec switch_root \"$NEWROOT\" \"$INIT\" $initargs" || {
+#    warn "Command:"
+#    warn capsh --drop=$CAPS_INIT_DROP -- -c "'"exec switch_root "$NEWROOT" "$INIT" $initargs"'"
+#    warn "failed."
+#    emergency_shell
+#    }
+#else
+#    exec switch_root "$NEWROOT" "$INIT" $initargs || {
+#    warn "Something went very badly wrong in the initramfs.  Please "
+#    warn "file a bug against ."
+#    emergency_shell
+#    }
+#fi
+
+#umount /proc /sys /dev/pts /dev/shm
+mkdir $OLDROOT
+#unshare -m
+mount --bind / $NEWROOT/$OLDROOT
+#setsid -c -w /bin/bash
+
+# Mount some important things
+mount -t proc -o nosuid,noexec,nodev proc $NEWROOT/proc >/dev/null 2>&1
+mount -t sysfs -o nosuid,noexec,nodev sysfs $NEWROOT/sys >/dev/null 2>&1
+mount -t devpts -o gid=5,mode=620 devpts $NEWROOT/dev/pts >/dev/null 2>&1
+mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs $NEWROOT/dev/shm >/dev/null 2>&1
+
+cd $NEWROOT
+#pivot_root . $OLDROOT
+
+chroot . "/bin/bash"
+
+#sh -c "umount /old_root; exec /sbin/init" <dev/console >dev/console 2>&1
+
+while :; do
+   setsid -c -w /bin/bash
+   echo "Spawning new shell ... "
+done
 
 # EOF
diff --git a/scripts/make_initramfs b/scripts/make_initramfs
--- a/scripts/make_initramfs
+++ b/scripts/make_initramfs
@@ -14,6 +14,33 @@ echo " Making initramfs from '$TARGDIR'  "
 echo "-------------------------------------"
 echo
 
+if [ ! -f $KEYGET ] ; then
+    echo "Please exceute 'make apps' first."
+    exit 1;
+fi
+
+if [ ! -d $TARGDIR ]; then
+    echo "No initramfs files yet."
+    exit 1
+fi
+
+# Syntax check init
+bash -n ./initramfs/init; ERR=$?
+if [ "$ERR" != "0" ] ; then
+    echo "Syntax error in init"
+    exit 1
+fi
+bash -n ./initramfs/shlib/comlin.sh; ERR=$?
+if [ "$ERR" != "0" ] ; then
+    echo "Syntax error in comlin.sh"
+    exit 1
+fi
+bash -n ./initramfs/shlib/functions.sh; ERR=$?
+if [ "$ERR" != "0" ] ; then
+    echo "Syntax error in functions.sh"
+    exit 1
+fi
+
 # Gather apps into initramfs
 
 cp $APPDIR/keyget/keyget $TARGDIR/bin
@@ -23,14 +50,7 @@ cp $APPDIR/reboot/linux_poweroff $TARGDIR/bin
 # Make initramfs from custom booter. The initrd is phased out
 # so we are making a custom one for auto bootdrive search
 
-if [ ! -d $TARGDIR ]; then
-    echo "No initramfs files yet."
-    exit
-fi
-
-#chown -R root.root $TARGDIR
-
-echo -n "Assemble cpio archive ... "
+echo -n "Assembling cpio archive ... "
 (cd $TARGDIR; find . | cpio -o -H newc | gzip) > $RAMFSRES
 echo "Geneated:" $RAMFSRES
 
diff --git a/scripts/make_iso b/scripts/make_iso
--- a/scripts/make_iso
+++ b/scripts/make_iso
@@ -29,10 +29,29 @@ mkdir -p $ROOTFS/boot
 #rm -rf $ROOTFS/boot/*
 #cp $SCRIPTS/misc/files/memtest86.bin $ROOTFS
 
+# See if conditions are met
+
+if [ ! -f $KEYGET ] ; then
+    echo "Must have apps / scripts built first (missing keyget)"
+    exit 1
+fi
+if [ ! -f $KERNELDIR/vmlinuz ] ; then
+    echo "Execute 'make getkern' first."
+    exit 1
+fi
+
+if [ ! -f $KERNELDIR/initramfs ] ; then
+    echo "Execute 'make initramfs' first."
+    exit 1
+fi
+
 echo -n "Copying filesystem ... "
-#rsync -ahu --progress ../comlin-usb-000/* $ROOTFS
-cp -a $LITEUSB/* $ROOTFS
+#rsync -ahu --progress $LITEUSB/* $ROOTFS
+cp -au $LITEUSB/* $ROOTFS
 echo OK
+
+# Pivot root needs this
+mkdir -p $ROOTFS/var/oldroot
 
 echo -n "Copying boot items ... "
 cp -r $KERNELDIR/* $ROOTFS/boot
